version: '3'
services:
  dockerapp:
    build: .
    ports: 
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - dockerapp_network
  redis:
    image: redis:3.2.0
    networks:
      - dockerapp_network
networks:
  dockerapp_network:
    driver: bridge
