version: '3'
services:
  rails:
    image: zalapeach/zalarails:0.1
    ports:
      - "3000:3000"
    volumes:
      - /home/zala/Desktop/WORK/projects/zalapeach:/home/zala/projects/zalapeach
    links:
      - pgdb
      - jenkins
  pgdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=tamarindo
    volumes:
      - /home/zala/Desktop/WORK/volumes/zalapeach_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/zala/Desktop/WORK/volumes/jenkins:/var/jenkins_home
